config/routes.rb
Rails.application.routes.draw do
  root to: "game#index"
  get "/play" => "game#new", as: :new_game
  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chess_board.rb
class ChessBoard < ActiveRecord::Base
  belongs_to :opponent, class_name: User.name, foreign_key: :opponent_id
  belongs_to :owner_board, class_name: User.name, foreign_key: :owner_board_id

  # validates :moves_arr, presence: true

  enum owner_board_color: {black: BLACK, white: WHITE}
  enum board_status: {in_game: 1, draw: 2, finished: 3}

  scope :find_playing_board, -> user_id do
    opponent_id = opponent_for user_id
    where(board_status: :in_game).where("owner_board_id = ? AND opponent_id = ?
      OR owner_board_id = ? AND opponent_id = ?", user_id, opponent_id, opponent_id, user_id).last
  end

  class << self
    def find_opponent_for user
      if opponent = REDIS.spop("seeks")
        if opponent != user
          owner_board_color = [WHITE, BLACK].shuffle.first
          board = ChessBoard.create!(owner_board_id: user,
            opponent_id: opponent, owner_board_color: owner_board_color,
            board_status: :in_game, moves_arr: "[]")
          board.start
        end
      else
        REDIS.sadd("seeks", user)
      end
    end
  end

  def start
    ActionCable.server.broadcast "player_#{self.owner_board_id}",
      {action: "game_start", msg: "#{self.owner_board_color}"}
    ActionCable.server.broadcast "player_#{self.opponent_id}",
      {action: "game_start", msg: "#{self.opponent_board_color}"}
  end

  def forfeit user
    if winner = opponent_for(user)
      if self.update_attributes board_status: :finished, winner_id: winner
        ActionCable.server.broadcast "player_#{winner}",
          {action: "opponent_forfeits", msg: "Opponent disconnected, you win!", type: "game-over"}
      end
    end
  end

  def opponent_for user
    return opponent_id if user == owner_board_id
    owner_board_id
  end

  def make_move user, data
    game = Chess::Game.new game: YAML.load(moves_arr)
    move_string = "#{data["move"]["from"]}#{data["move"]["to"]}"
    if !game.full_move move_string
      opponent = opponent_for user
      status = data["status"].split("-")[0]
      type = data["status"].split("-")[1]
      move_string = "#{data["move"]["from"]}-#{data["move"]["to"]}"
      self.update_attribute :moves_arr, game.moves.to_s
      ActionCable.server.broadcast "player_#{opponent}",
        {action: "make_move", move: move_string, msg: status, type: type}
    end
  end

  def game_over user, data
    opponent = opponent_for user
    status = data["status"].split("-")[0]
    type = data["status"].split("-")[1]
    winner = data["type"] == "checkmate" ? user : nil
    if self.update_attributes board_status: :finished, winner_id: winner
      ActionCable.server.broadcast "player_#{opponent}",
        {action: "game_over", msg: status, type: type}
    end
  end

  def opponent_board_color
    white? ? BLACK : WHITE
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable
  validates :last_name, :first_name, presence: true

  def full_name
    "#{last_name} #{first_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
      :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
      :password_confirmation, :current_password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/new.html.erb
<% content_for :channels do %>
  <%= javascript_include_tag "channels/game" %>
<% end %>
<div id="game-play">
  <div id="chessboard" style="width: 600px"></div>
  <div id="game-status"></div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-header">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <%= link_to "Chess", root_path, id: "logo" %>
      </div>
      <div class="col-md-7">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Play", new_game_path, class: "active" %></li>
              <li class="dropdown">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.full_name %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <%= render "layouts/login_form" %>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_login_form.html.erb
<%= form_for(:user, url: session_path(:user)) do |f| %>
  <div class="row login_row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, class: "form-control login_input" %>
    </div>

    <div class="col-md-4">
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "off", class: "form-control login_input" %>
    </div>
    <div class="col-md-2">
      <%= f.submit "Log in", class: "btn btn-primary form-control login_input" %>
    </div>
  </div>
  <div class="row forgot-pass">
    <div class="col-md-5 col-md-offset-2">
      <%= link_to "Forgot your password?", new_password_path(:user) %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChess</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.10.2/chess.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :channels %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |type, message| %>
        <% if message %>
          <div class="alert fade in flash-notice">
            <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
            <p class="text-center flash-message"><%= message %></p>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>